package DavideSalzani.ImmobiliareProjectBE.supportClasses.supportEnum;

public enum TypeOfProperty {
    RUSTICO, APPARTAMENTO, CASA_INDIPENDENTE, BIFAMILIARE, ATTICO, CONDOMINIO, VILLA, TRIFAMILIARE, MONOLOCALE, BILOCALE, TRILOCALE, QUADRILOCALE, LOFT, MANSARDA, CASALE, PALAZZO, CHALET, CAPANNONE, NEGOZIO, UFFICIO, TERRENO_EDIFICABILE, TERRENO_AGRICOLO
}
